### ISSUE TITLE
Make the project name include (`.` dot)

### ISSUE THREAD

**Issue by iyulab-caveman** [unoplatform/uno.templates#171] opened 2023-07-11 00:50 UTC
## What would you like to be added:
Make sure to include (`.` dot) in your project name to fully utilize the namespace.

## Why is this needed:
I want it to be consistent with the namespaces of other foundation libraries that don't have UNO dependencies.
This is UnoApp
MyProduct (models)
MyProduct.UnoApp
MyProduct.WebApp
MyProduct.DesktopApp
MyProduct.... 
I'd like to have it follow a structure like this
This is an accepted convention in other .NET projects.

## For which Platform:

- [x] iOS
- [x ] Android
- [x] WebAssembly
- [x] WebAssembly renders for Xamarin.Forms
- [x] Windows
- [ ] Build tasks

## Anything else we need to know?
no

**Comment by jeromelaban** [comment] 2023-07-11 13:14
Thanks for the report. I'm not sure to understand what change you're suggesting. What's in the default naming that is causing trouble?

**Comment by dansiegel** [comment] 2023-07-11 14:23
@jeromelaban the issue comes from `MyExtensionsApp._1` we've been trying to find the right balance of supporting certain project names that contain special characters without causing additional issues with resource loading. This is an ongoing issue @nickrandolph and I have been investigating.

**Comment by dansiegel** [comment] 2023-08-03 21:20
Closing this as a duplicate of #94

**Closed by dansiegel** 2023-08-03 21:20 UTC
Labels: kind/enhancement, triage/duplicate, triage/untriaged

**Comment by hawkerm** [comment] 2024-03-31 04:53
@dansiegel I think this is asking that it should be able to contain `.`. I was surprised going that I couldn't when I used the new template. I generally add `.App` to the end of my UI projects so that I can have it at the top of my solution and other related dependent library projects follow `NameOfApp.Whatever` for Services or Models, etc...

It'd be nice to ensure that having dots in project names are supported as many .NET projects follow this pattern/convention.
