### ISSUE TITLE
[Bug] Creating cross-runtime library doesn't create a sln file

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno.templates#530] opened 2024-01-25 18:19 UTC
### Current behavior

`dotnet new unolib-crossruntime` doesn't create solution file

### Expected behavior

It should create

### Template Host

dotnet new

### Host OS

Windows

### Template Options

-

### Template Version

```shell
5.2.0-dev.19
```

**Comment by dansiegel** [comment] 2024-01-26 15:22
Closing this as I am unable to reproduce the issue.

<img width="765" alt="Screenshot 2024-01-26 at 9 21 24 AM" src="https://github.com/unoplatform/uno.templates/assets/3860573/720074ab-ee6d-4233-b2cc-9a6b3bd15628">

**Closed by dansiegel** 2024-01-26 15:22 UTC
Labels: kind/bug, triage/untriaged
