### ISSUE TITLE
[Bug] Unable to resolve Uno.Sdk for unolib

### ISSUE THREAD

**Issue by Takoooooo** [unoplatform/uno.templates#675] opened 2024-05-07 14:52 UTC
### Current behavior

Currently when you instantiate the unolib template in Rider csproj will fail to load because it couldn't locate the Uno.Sdk.

### Expected behavior

unolib template in Rider could be instantiated succsessfully and it loads correctly.

### Template Host

Rider

### Host OS

Windows

### Template Options

All template options are used with the default values, nothing has changed. 

### Template Version

```shell
5.2.31 version of templates is used
```

### Anything else we need to know?

I guess we should include visualStudioSdkWorkaround parameter as we do for other templates in order to fix that

**Comment by jeromelaban** [comment] 2024-05-07 15:01
Interesting. In this particular context, the global.json in the folder should be enough, as the issue reported for `visualStudioSdkWorkaround` should only be valid for VS and 8.0.100.

Does restore work for your in the CLI?

**Comment by Takoooooo** [comment] 2024-05-07 15:04
@jeromelaban dotnet restore says that restore is completed successfully but when i try to re-load the project i get the same error

**Comment by Takoooooo** [comment] 2024-05-07 15:09
Btw, the same issue happens when i instantiate that template from VS, but i didn't include it in the description since Dan is going to exclude CLI templates to be shown in VS

**Comment by jeromelaban** [comment] 2024-05-07 18:28
Thanks. Which version of visual studio are you running, and which version of the dotnet sdk are you using?

**Comment by Takoooooo** [comment] 2024-05-08 10:57
VS 17.9.6 Here is the list of sdks i have, i guess the last one is used
![image](https://github.com/unoplatform/uno.templates/assets/53405089/0943a605-0351-4073-a846-edd1cdab4082)

**Comment by jeromelaban** [comment] 2024-05-08 11:58
Thanks. This is very curious that VS is also showing this error. Could you show it in the context of VS? Also, do you have any custom feed that requires authentication?

**Comment by Takoooooo** [comment] 2024-05-08 13:01
Here how it works on my PC in VS
![Анимация1](https://github.com/unoplatform/uno.templates/assets/53405089/fe75723a-3c81-4747-94dc-a0d36226201c)
I have only nuget feed enabled, so no custom feeds

**Comment by jeromelaban** [comment] 2024-05-08 13:39
Thanks. Can you also post the generated folder in a zip here?

**Comment by Takoooooo** [comment] 2024-05-08 13:47
@jeromelaban Here it is [Unolib.zip](https://github.com/unoplatform/uno.templates/files/15249740/Unolib.zip)

**Comment by dansiegel** [comment] 2024-08-20 18:33
upon testing this more this seems like an issue with Visual Studio specifically. The issue is caused when the global.json is not in the directory with the solution file. I am going to close this issue as there isn't really something that we can do in the template itself however I will be opening issues for the Wizard experience to work around this.

**Closed by dansiegel** 2024-08-20 18:33 UTC
Labels: kind/bug, triage/untriaged
